version: 0.2
phases:
  install:
    commands:
      - echo install step...
  pre_build:
    commands:
      - echo logging in to AWS ECR...
      - $(aws ecr get-login --no-include-email --region us-east-1)
  build:
    commands:
      - echo build Docker image on `date`
      - docker build -t docker-nginx-app:latest .
      - docker tag docker-nginx-app:latest 984242085940.dkr.ecr.us-east-1.amazonaws.com/docker-nginx:latest
  post_build:
    commands:
      - echo build Docker image complete `date`
      - echo push latest Docker images to ECR...
      - docker push 984242085940.dkr.ecr.us-east-1.amazonaws.com/docker-nginx:latest
      - echo Writing image definitions file...
      - printf '[{"name":"docker-nginx","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
    files: imagedefinitions.json
